# Generated by Django 3.2a1 on 2022-02-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=225)),
                ('available_funds', models.CharField(max_length=222)),
                ('invested_funds', models.CharField(max_length=222)),
                ('account_balance', models.CharField(max_length=222)),
                ('total_profit', models.CharField(max_length=222)),
                ('open_postions', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=2555)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=222)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('document_upload', models.CharField(max_length=2222)),
                ('telegram_username', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(max_length=225)),
                ('farm_name', models.CharField(max_length=222)),
                ('monthly_interest', models.CharField(max_length=222)),
                ('terms', models.CharField(max_length=222)),
                ('roi', models.CharField(max_length=222)),
                ('apy', models.CharField(max_length=222)),
                ('farm_description', models.CharField(max_length=222)),
            ],
        ),
    ]
