# Generated by Django 3.2a1 on 2022-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=225)),
                ('user_id', models.CharField(max_length=222)),
                ('transaction_type', models.CharField(max_length=222)),
                ('amount', models.CharField(max_length=222)),
                ('date', models.CharField(max_length=222)),
            ],
        ),
    ]
