# Generated by Django 3.2a1 on 2022-02-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0003_kyc_user_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farms',
            new_name='Farm',
        ),
    ]
