# Generated by Django 3.2a1 on 2022-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0005_auto_20220228_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='id',
        ),
        migrations.AlterField(
            model_name='farm',
            name='apy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='monthly_interest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farm',
            name='roi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farm',
            name='terms',
            field=models.IntegerField(),
        ),
    ]
