# Generated by Django 3.2a1 on 2022-02-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalIinfo',
            new_name='PersonalInfo',
        ),
    ]
