# Generated by Django 3.2a1 on 2022-02-22 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_personaliinfo_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='telegram_username',
            field=models.CharField(default=django.utils.timezone.now, max_length=222),
            preserve_default=False,
        ),
    ]
