# Generated by Django 3.2a1 on 2022-02-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_personalinfo_telegram_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='telegram_username',
        ),
    ]
