# Generated by Django 3.2a1 on 2022-02-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220222_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='phone_number',
            field=models.CharField(max_length=2555),
        ),
    ]
