# Generated by Django 3.2a1 on 2022-02-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_personal_info_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=225)),
                ('available_funds', models.CharField(max_length=222)),
                ('invested_funds', models.CharField(max_length=222)),
                ('account_balance', models.CharField(max_length=222)),
                ('total_profit', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='Investment_scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_scheme', models.CharField(max_length=222)),
                ('user_id', models.CharField(max_length=222)),
                ('order_id', models.CharField(max_length=222)),
                ('capital_invested', models.CharField(max_length=222)),
                ('investment_status', models.CharField(max_length=222)),
                ('daily_profit', models.CharField(max_length=222)),
                ('net_profit', models.CharField(max_length=222)),
                ('total_return', models.CharField(max_length=222)),
                ('profit_earned', models.CharField(max_length=222)),
                ('term_of_scheme', models.CharField(max_length=222)),
                ('term_begins', models.CharField(max_length=222)),
                ('term_ends', models.CharField(max_length=222)),
                ('order_date', models.CharField(max_length=222)),
                ('approved_date', models.CharField(max_length=222)),
                ('payment_method', models.CharField(max_length=222)),
                ('payment_status', models.CharField(max_length=222)),
                ('conversion_fee', models.CharField(max_length=222)),
            ],
        ),
    ]
