# Generated by Django 3.2a1 on 2022-02-23 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_account_investment_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='open_postions',
            field=models.CharField(default=django.utils.timezone.now, max_length=222),
            preserve_default=False,
        ),
    ]
