# Generated by Django 3.2a1 on 2022-02-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_account_open_postions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment_scheme',
            old_name='daily_profit',
            new_name='monthly_profit',
        ),
    ]
