# Generated by Django 3.2a1 on 2022-02-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_daily_profit_investment_scheme_monthly_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(max_length=225)),
                ('farm_name', models.CharField(max_length=222)),
                ('monthly_interest', models.CharField(max_length=222)),
                ('terms', models.CharField(max_length=222)),
                ('roi', models.CharField(max_length=222)),
                ('apy', models.CharField(max_length=222)),
                ('farm_description', models.CharField(max_length=222)),
            ],
        ),
    ]
