# Generated by Django 3.2a1 on 2022-02-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_farms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc_user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=2555)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=222)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('document_upload', models.CharField(max_length=2222)),
                ('telegram_username', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=225)),
                ('user_id', models.CharField(max_length=222)),
                ('transaction_type', models.CharField(max_length=222)),
                ('amount', models.CharField(max_length=222)),
                ('date', models.CharField(max_length=222)),
            ],
        ),
        migrations.DeleteModel(
            name='Farms',
        ),
    ]
