# Generated by Django 3.2a1 on 2022-03-01 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220228_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_scheme',
            name='approval',
            field=models.CharField(default=django.utils.timezone.now, max_length=222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_info',
            name='blocked',
            field=models.CharField(default=django.utils.timezone.now, max_length=222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='approval',
            field=models.CharField(default=django.utils.timezone.now, max_length=222),
            preserve_default=False,
        ),
    ]
