# Generated by Django 3.2a1 on 2022-03-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_account_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_scheme',
            name='capital_invested',
            field=models.IntegerField(),
        ),
    ]
