# Generated by Django 3.2a1 on 2022-03-09 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_alter_investment_scheme_capital_invested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id',
            new_name='investment_id',
        ),
        migrations.RenameField(
            model_name='investment_scheme',
            old_name='id',
            new_name='investment_id',
        ),
        migrations.RemoveField(
            model_name='investment_scheme',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='investment_scheme',
            name='conversion_fee',
        ),
        migrations.RemoveField(
            model_name='investment_scheme',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='investment_scheme',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='investment_scheme',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='investment_scheme',
            name='profit_earned',
        ),
        migrations.RemoveField(
            model_name='investment_scheme',
            name='total_return',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='reciept_upload',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='account',
            name='available_funds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='invested_funds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='open_postions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_profit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.personal_info'),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='approved_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='investment_status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('inactive', 'inactive')], max_length=222),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='monthly_profit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='net_profit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='term_begins',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='term_ends',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='term_of_scheme',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
