# Generated by Django 3.2a1 on 2022-03-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0006_auto_20220309_2112'),
        ('user', '0017_alter_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_scheme',
            name='name_of_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.farm'),
        ),
    ]
