# Generated by Django 3.2a1 on 2022-03-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_investment_scheme_name_of_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_scheme',
            name='name_of_scheme',
            field=models.CharField(max_length=222),
        ),
    ]
