# Generated by Django 3.2a1 on 2022-03-17 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_investment_scheme_name_of_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment_scheme',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='date',
        ),
        migrations.AddField(
            model_name='investment_scheme',
            name='initiation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment_scheme',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='initiation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
