# Generated by Django 3.2a1 on 2022-03-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20220317_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_scheme',
            name='net_profit',
            field=models.IntegerField(blank=True),
        ),
    ]
