# Generated by Django 3.2a1 on 2022-03-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_investment_scheme_net_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_scheme',
            name='monthly_profit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='net_profit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='investment_scheme',
            name='term_of_scheme',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
